#!/bin/bash

RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m'

if [ $# -eq 0 ]
  then echo -e "${RED}Usage: convert <filename.pdf>${NC}\n"
  exit
fi

infile=$1
outfile=$2

if [ $# -eq 2 ]
  then echo -e "${GREEN}Converting $infile to $outfile\n${NC}";
else 
  echo -e "${GREEN}Converting $infile to out.txt\n${NC}"
fi

php=`which php`

$php bin/run.php $infile

echo -e "${GREEN}Conversion complete.\n${NC}";